# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configuration_path.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPalette,QBrush,QPixmap

class Ui_PathConfi(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(650, 350)
        Form.setMinimumSize(QtCore.QSize(650, 350))
        Form.setMaximumSize(QtCore.QSize(650, 350))
#         Form.setStyleSheet("#Form{\n"
# "\n"
# "border-image:url(:/mainwindow/otherbg.jpg)\n"
# "}\n"
# "\n"
# "")
        palette = QPalette()
        palette.setBrush(QPalette.Background, QBrush(QPixmap('userInterface/haoche.jpg')))
        Form.setPalette(palette)

        self.agentPath = QtWidgets.QPushButton(Form)
        self.agentPath.setGeometry(QtCore.QRect(178, 71, 41, 41))
        self.agentPath.setStyleSheet("border-image:url(:/mainwindow/filepath.jpg)")
        self.agentPath.setText("")
        self.agentPath.setObjectName("agentPath")

        self.agentPath.hide()

        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(230, 70, 381, 41))
        self.lineEdit_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.lineEdit_3.hide()


        self.carlaPath = QtWidgets.QPushButton(Form)
        self.carlaPath.setGeometry(QtCore.QRect(180, 130, 41, 41))
        self.carlaPath.setStyleSheet("border-image:url(:/mainwindow/filepath.jpg)")
        self.carlaPath.setText("")
        self.carlaPath.setObjectName("carlaPath")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 141, 31))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(230, 130, 381, 41))
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 70, 151, 41))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.okPath = QtWidgets.QPushButton(Form)
        self.okPath.setGeometry(QtCore.QRect(170, 220, 141, 41))
        self.okPath.setStyleSheet("QPushButton{\n"
"    border-radius:25px;\n"
"    background-color:rgb(255, 255, 255); \n"
"    color: rgb(0, 170, 255)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color:rgb(173, 115, 0)\n"
"}")
        self.okPath.setObjectName("okPath")
        self.okPath.clicked.connect(self.close)
        self.canclepath = QtWidgets.QPushButton(Form)
        self.canclepath.setGeometry(QtCore.QRect(350, 220, 141, 41))
        self.canclepath.setStyleSheet("QPushButton{\n"
"    border-radius:25px;\n"
"    background-color:rgb(255, 255, 255); \n"
"    color: rgb(0, 170, 255)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color:rgb(173, 115, 0)\n"
"}")
        self.canclepath.setObjectName("canclepath")
        self.canclepath.clicked.connect(self.close)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Configuration"))
        self.label_2.setText(_translate("Form", "Carla Path:"))
        # self.label.setText(_translate("Form", "Agent Path:"))
        self.okPath.setText(_translate("Form", "OK"))
        self.canclepath.setText(_translate("Form", "Cancle"))
import userInterface.background_rc
