# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1050, 550)
        MainWindow.setMinimumSize(QtCore.QSize(1050, 550))
        MainWindow.setMaximumSize(QtCore.QSize(1050, 550))
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"border-image:url(:/mainwindow/background.jpg)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PathSetting = QtWidgets.QPushButton(self.centralwidget)
        self.PathSetting.setGeometry(QtCore.QRect(100, 190, 300, 65))
        self.PathSetting.setMinimumSize(QtCore.QSize(300, 65))
        self.PathSetting.setMaximumSize(QtCore.QSize(300, 65))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(24)
        self.PathSetting.setFont(font)
        self.PathSetting.setStyleSheet("QPushButton{\n"
"    border-radius:25px;\n"
"    background-color:rgb(255, 255, 255);\n"
"    color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color:rgb(173, 115, 0)\n"
"}")
        self.PathSetting.setObjectName("Path Setting")
        self.HistoryTestRecord = QtWidgets.QPushButton(self.centralwidget)
        self.HistoryTestRecord.setGeometry(QtCore.QRect(90, 390, 300, 60))
        self.HistoryTestRecord.setMinimumSize(QtCore.QSize(300, 60))
        self.HistoryTestRecord.setMaximumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(24)
        self.HistoryTestRecord.setFont(font)
        self.HistoryTestRecord.setStyleSheet("QPushButton{\n"
"    border-radius:25px;\n"
"    background-color:rgb(255, 255, 255);\n"
"    color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color:rgb(173, 115, 0)\n"
"}")
        self.HistoryTestRecord.setObjectName("HistoryTestRecord")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 390, 61, 61))
        self.label.setStatusTip("")
        self.label.setWhatsThis("")
        self.label.setStyleSheet("border-image:url(:/mainwindow/record.jpg)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.CarlaRun = QtWidgets.QPushButton(self.centralwidget)
        self.CarlaRun.setGeometry(QtCore.QRect(550, 390, 171, 51))
        self.CarlaRun.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(24)
        self.CarlaRun.setFont(font)
        self.CarlaRun.setStyleSheet("QPushButton{\n"
"    border-radius:25px;\n"
"    background-color:rgb(255, 255, 255); \n"
"    color: rgb(0, 170, 255)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color:rgb(173, 115, 0)\n"
"}")
        self.CarlaRun.setFlat(False)
        self.CarlaRun.setObjectName("CarlaRun")
        self.AgentSelection = QtWidgets.QPushButton(self.centralwidget)
        self.AgentSelection.setGeometry(QtCore.QRect(100, 290, 300, 60))
        self.AgentSelection.setMinimumSize(QtCore.QSize(300, 60))
        self.AgentSelection.setMaximumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(24)
        self.AgentSelection.setFont(font)
        self.AgentSelection.setStyleSheet("QPushButton{\n"
"    border-radius:25px;\n"
"    background-color:rgb(255, 255, 255);\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"  background-color:rgb(173, 115, 0)\n"
"}")
        self.AgentSelection.setFlat(False)
        self.AgentSelection.setObjectName("AgentSelection")
        self.Run = QtWidgets.QPushButton(self.centralwidget)
        self.Run.setGeometry(QtCore.QRect(790, 390, 170, 50))
        self.Run.setMinimumSize(QtCore.QSize(170, 50))
        self.Run.setMaximumSize(QtCore.QSize(170, 50))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(24)
        self.Run.setFont(font)
        self.Run.setStyleSheet("QPushButton{\n"
"    border-radius:25px;\n"
"    background-color:rgb(255, 255, 255); \n"
"    color: rgb(0, 170, 255)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"  background-color:rgb(173, 115, 0)\n"
"}")
        self.Run.setCheckable(False)
        self.Run.setObjectName("Run")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 190, 61, 61))
        self.label_2.setStatusTip("")
        self.label_2.setWhatsThis("")
        self.label_2.setStyleSheet("border-image:url(:/mainwindow/pathsetting.png)")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 290, 61, 61))
        self.label_3.setStatusTip("")
        self.label_3.setWhatsThis("")
        self.label_3.setStyleSheet("border-image:url(:/mainwindow/agentselection.png)")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(490, 10, 40, 40))
        self.label_4.setMinimumSize(QtCore.QSize(40, 40))
        self.label_4.setMaximumSize(QtCore.QSize(40, 40))
        self.label_4.setStatusTip("")
        self.label_4.setWhatsThis("")
        self.label_4.setStyleSheet("border-image:url(:/mainwindow/timgday.jpg)")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(580, 10, 40, 40))
        self.label_5.setMinimumSize(QtCore.QSize(40, 40))
        self.label_5.setMaximumSize(QtCore.QSize(40, 40))
        self.label_5.setStatusTip("")
        self.label_5.setWhatsThis("")
        self.label_5.setStyleSheet("border-image:url(:/mainwindow/timgnight.jpg)")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(720, 10, 40, 40))
        self.label_6.setMinimumSize(QtCore.QSize(40, 40))
        self.label_6.setMaximumSize(QtCore.QSize(40, 40))
        self.label_6.setStatusTip("")
        self.label_6.setWhatsThis("")
        self.label_6.setStyleSheet("border-image:url(:/mainwindow/timgcloud.jpg)")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(780, 10, 40, 40))
        self.label_7.setMinimumSize(QtCore.QSize(40, 40))
        self.label_7.setMaximumSize(QtCore.QSize(40, 40))
        self.label_7.setStatusTip("")
        self.label_7.setWhatsThis("")
        self.label_7.setStyleSheet("border-image:url(:/mainwindow/timgrainf.jpg)")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(840, 10, 40, 35))
        self.label_8.setMinimumSize(QtCore.QSize(40, 35))
        self.label_8.setMaximumSize(QtCore.QSize(35, 35))
        self.label_8.setStatusTip("")
        self.label_8.setWhatsThis("")
        self.label_8.setStyleSheet("border-image:url(:/mainwindow/timgwind.jpg)")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.WeatherAndT = QtWidgets.QRadioButton(self.centralwidget)
        self.WeatherAndT.setGeometry(QtCore.QRect(10, 30, 401, 21))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.WeatherAndT.setFont(font)
        self.WeatherAndT.setStyleSheet("color:rgb(255, 255, 255);\n"
"")
        self.WeatherAndT.setObjectName("WeatherAndT")
        self.Timer = QtWidgets.QComboBox(self.centralwidget)
        self.Timer.setGeometry(QtCore.QRect(510, 60, 115, 27))
        self.Timer.setMinimumSize(QtCore.QSize(0, 0))
        self.Timer.setMaximumSize(QtCore.QSize(10000, 10000))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(14)
        self.Timer.setFont(font)
        self.Timer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Timer.setAutoFillBackground(False)
        self.Timer.setStyleSheet("QComboBox{\n"
"    \n"
"    background-color:rgb(255, 255, 255);\n"
"    \n"
"}")
        self.Timer.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Singapore))
        self.Timer.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.Timer.setDuplicatesEnabled(False)
        self.Timer.setObjectName("Timer")
        self.Timer.addItem("")
        self.Timer.addItem("")
        self.Timer.addItem("")
        self.Timer.addItem("")
        self.Weather_CB = QtWidgets.QComboBox(self.centralwidget)
        self.Weather_CB.setGeometry(QtCore.QRect(720, 60, 87, 27))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(14)
        self.Weather_CB.setFont(font)
        self.Weather_CB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Weather_CB.setAutoFillBackground(False)
        self.Weather_CB.setStyleSheet("QComboBox{\n"
"    \n"
"    background-color:rgb(255, 255, 255);\n"
"    \n"
"}")
        self.Weather_CB.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Singapore))
        self.Weather_CB.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.Weather_CB.setDuplicatesEnabled(False)
        self.Weather_CB.setObjectName("Weather_CB")
        self.Weather_CB.addItem("")
        self.Weather_CB.addItem("")
        self.Weather_CB.addItem("")
        self.Weather_CB.addItem("")
        self.CustoizeWAndT = QtWidgets.QRadioButton(self.centralwidget)
        self.CustoizeWAndT.setGeometry(QtCore.QRect(10, 100, 381, 21))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.CustoizeWAndT.setFont(font)
        self.CustoizeWAndT.setStyleSheet("color:rgb(255, 255, 255);\n"
"")
        self.CustoizeWAndT.setObjectName("CustoizeWAndT")
        self.Customize = QtWidgets.QPushButton(self.centralwidget)
        self.Customize.setGeometry(QtCore.QRect(600, 50, 200, 51))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(20)
        self.Customize.setFont(font)
        self.Customize.setStyleSheet("QPushButton{\n"
"    border-radius:25px;\n"
"    background-color:rgb(255, 255, 255);\n"
"    color:black;\n"
"}\n"
"QPushButton:pressed{\n"
"  background-color:rgb(173, 115, 0)\n"
"}")
        self.Customize.setObjectName("Customize")
        self.Scenario = QtWidgets.QLabel(self.centralwidget)
        self.Scenario.setGeometry(QtCore.QRect(420, 220, 141, 61))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(24)
        self.Scenario.setFont(font)
        self.Scenario.setStyleSheet("color:rgb(255, 255, 255);\n"
"\n"
"")
        self.Scenario.setObjectName("Scenario")
        self.ScenearioSelection = QtWidgets.QComboBox(self.centralwidget)
        self.ScenearioSelection.setGeometry(QtCore.QRect(580, 230, 421, 51))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(20)
        self.ScenearioSelection.setFont(font)
        self.ScenearioSelection.setStyleSheet("QComboBox{\n"
"    \n"
"    background-color:rgb(255, 255, 255);\n"
"    \n"
"}")
        self.ScenearioSelection.setObjectName("ScenearioSelection")
        self.ScenearioSelection.addItem("")
        self.ScenearioSelection.addItem("")
        self.ScenearioSelection.addItem("")
        self.ScenearioSelection.addItem("")
        self.ScenearioSelection.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Timer.setCurrentIndex(0)
        self.Weather_CB.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        self.PathSetting.setText(_translate("MainWindow", "Path Setting"))
        self.HistoryTestRecord.setText(_translate("MainWindow", "History Test Record"))
        self.CarlaRun.setText(_translate("MainWindow", "Carla Run"))
        self.AgentSelection.setText(_translate("MainWindow", "Agent Selection"))
        self.Run.setText(_translate("MainWindow", "Run"))
        self.WeatherAndT.setText(_translate("MainWindow", "Pre-defined Weather and Time"))
        self.Timer.setItemText(0, _translate("MainWindow", "Moring"))
        self.Timer.setItemText(1, _translate("MainWindow", "Noon"))
        self.Timer.setItemText(2, _translate("MainWindow", "Sunset"))
        self.Timer.setItemText(3, _translate("MainWindow", "Midnight"))
        self.Weather_CB.setItemText(0, _translate("MainWindow", "Clear"))
        self.Weather_CB.setItemText(1, _translate("MainWindow", "Rainy"))
        self.Weather_CB.setItemText(2, _translate("MainWindow", "Fog"))
        self.Weather_CB.setItemText(3, _translate("MainWindow", "Wind"))
        self.CustoizeWAndT.setText(_translate("MainWindow", "Customize Weather and Time"))
        self.Customize.setText(_translate("MainWindow", "Customize"))
        self.Scenario.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400; font-style:italic;\">Scenario :</span></p></body></html>"))
        self.ScenearioSelection.setItemText(0, _translate("MainWindow", "Leading Vehicle Scenario"))
        self.ScenearioSelection.setItemText(1, _translate("MainWindow", "Object Detection Scenario"))
        self.ScenearioSelection.setItemText(2, _translate("MainWindow", "Traffic Light Detection Scenario"))
        self.ScenearioSelection.setItemText(3, _translate("MainWindow", "Turning Obstacle Scenario"))
        self.ScenearioSelection.setItemText(4, _translate("MainWindow", "Blind Point Scenario"))
import userInterface.background_rc
